/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.8 */
/* Mon Oct 27 10:39:40 2025 */

/* parameterized module instance */
fifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
